# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: Juan
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - Juan/watermark
      - Juan/Muneris

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Juan Visbal"

# Avatar image path
avatar: "./images/profile.png"

# Name section text
name: "Juan Visbal"

# Tagline section text
tagline: >-
    ðŸ‘‹ I'm Juan from Colombia ðŸ‡¨ðŸ‡´
    10+ years of experience as a software engineer and Shopify Expert, currently a Team Leader at SLTWTR Creative Agency. I'm passionate about sustainable innovation in tech. 

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-briefcase"
      text: "SLTWTR Creative Agency"
      url: "https://sltwtr.com"
      alt: "SLTWTR is a nimble team of designer-developers that come from the worlds of branding and lifestyle. We offer design and technology services along with digital tools, built specifically for lifestyle-inspired apparel ecommerce."
      title: "SLTWTR is a nimble team of designer-developers that come from the worlds of branding and lifestyle. We offer design and technology services along with digital tools, built specifically for lifestyle-inspired apparel ecommerce."
      target: "_blank"
  - link:
      icon: "fa-solid fa-link"
      text: "Bento"
      url: "https://bento.me/juan"
      alt: "Find me around the web with Bento"
      title: "Find me around the web"
      target: "_blank"
  - link:
      icon: "fa-solid fa-file-lines"
      text: "Resume"
      url: "https://juanvisbal.com/resume"
      alt: "Juan's Resume"
      title: "Juan's Resume"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/juanvisbalco"
      title: "Juan's GitHub"
      alt: "Juan's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/juanvisbalco/"
      title: "Juan's LinkedIn"
      alt: "Juan's LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/@juanvisbal.com"
      title: "Juan's Bluesky"
      alt: "Juan's Bluesky"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://twitter.com/juanvisbalco"
      title: "Juan's Twitter"
      alt: "Juan's Twitter"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/juanvisbalco/"
      title: "Instagram"
      alt: "Juan's Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-letterboxd"
      url: "http://letterboxd.com/juanvisbal"
      title: "Juan's Letterboxd"
      alt: "Juan's Letterboxd"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:me@juanvisbal.com"
      title: "Email: me@juanvisbal.com"
      alt: "me@juanvisbal.com"
      target: "_blank"
      

# Footer text
footer: >
    He/They Â· ðŸ³ï¸â€ðŸŒˆ Â· BogotÃ¡, Colombia

# Footer copyright message
# Linkyee is a 100% free, open-source projectâ€”feel free to modify the copyright message as you like. :)
copyright: >
  Â© 2024 <a href="juanvisbal.com" target="_blank">Juan Visbal</a>. Powered by <a href="https://github.com/juanvisbalco/linkyee" target="_blank">linkyee</a>
